"""FastAPI application entry point: lifespan, CORS, routers, error handling."""

from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

# Atlassian client utilities
from app.clients.atlassian import AtlassianError, build_client, set_client

# Application configuration
from app.core.config import get_settings

# API route modules
from app.routers import health, reports, teams


# -----------------------------------------------------------
# Application Lifespan
# Runs once when the application starts and shuts down.
# Used to create and close the shared Atlassian HTTP client.
# -----------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = get_settings()

    # Create a shared HTTP client for Jira/Confluence
    client = build_client(settings)

    # Store globally so dependency providers can reuse it
    set_client(client)

    try:
        yield
    finally:
        # Close HTTP connections gracefully during shutdown
        await client.aclose()
        set_client(None)


# -----------------------------------------------------------
# Create FastAPI application
# -----------------------------------------------------------
app = FastAPI(
    title="Developer Activity Reporting API",
    version="1.0.0",
    description="Reads teams from Confluence and issues/workflow data from Jira.",
    lifespan=lifespan,
)

# Load environment settings
settings = get_settings()

# -----------------------------------------------------------
# Enable Cross-Origin Resource Sharing (CORS)
# Allows the React frontend to communicate with the backend.
# -----------------------------------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origin_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# -----------------------------------------------------------
# Helper function to return consistent JSON error responses.
#
# Example response:
# {
#   "error": {
#      "code": "...",
#      "message": "..."
#   }
# }
# -----------------------------------------------------------
def _error(status_code: int, code: str, message: str) -> JSONResponse:
    return JSONResponse(
        status_code=status_code,
        content={
            "error": {
                "code": code,
                "message": message,
            }
        },
    )


# -----------------------------------------------------------
# Handle custom Atlassian API errors.
#
# Converts Jira/Confluence exceptions into user-friendly
# JSON responses.
# -----------------------------------------------------------
@app.exception_handler(AtlassianError)
async def atlassian_error_handler(_: Request, exc: AtlassianError) -> JSONResponse:

    code = "atlassian_error"
    message = exc.message

    # Special handling for unsafe/unbounded JQL queries
    if exc.status_code == 400 and "unbounded" in message.lower():
        code = "unbounded_jql"
        message = (
            "Unbounded JQL is not allowed. "
            "The query must be restricted "
            "(e.g. by project and date range)."
        )

    # Authentication/authorization failure
    elif exc.status_code in (401, 403):
        code = "atlassian_auth"

    # Requested Jira/Confluence resource not found
    elif exc.status_code == 404:
        code = "not_found"

    return _error(exc.status_code, code, message)


# -----------------------------------------------------------
# Handle normal HTTP exceptions generated by FastAPI.
#
# Example:
# 404 Not Found
# 405 Method Not Allowed
# -----------------------------------------------------------
@app.exception_handler(StarletteHTTPException)
async def http_error_handler(
    _: Request,
    exc: StarletteHTTPException,
) -> JSONResponse:

    return _error(
        exc.status_code,
        "http_error",
        str(exc.detail),
    )


# -----------------------------------------------------------
# Handle request validation errors.
#
# Triggered when request parameters or request body
# do not match the expected schema.
# -----------------------------------------------------------
@app.exception_handler(RequestValidationError)
async def validation_error_handler(
    _: Request,
    exc: RequestValidationError,
) -> JSONResponse:

    return _error(
        422,
        "validation_error",
        str(exc.errors()),
    )


# -----------------------------------------------------------
# Catch any unexpected exception.
#
# Prevents stack traces from being exposed to clients.
# Returns a generic internal server error.
# -----------------------------------------------------------
@app.exception_handler(Exception)
async def unhandled_error_handler(
    _: Request,
    exc: Exception,
) -> JSONResponse:

    return _error(
        500,
        "internal_error",
        "An unexpected error occurred.",
    )


# -----------------------------------------------------------
# Register API routers
#
# Each router contains a related set of endpoints.
# -----------------------------------------------------------
app.include_router(health.router)
app.include_router(teams.router)
app.include_router(reports.router)


# -----------------------------------------------------------
# Root endpoint
#
# Returns basic API information.
# -----------------------------------------------------------
@app.get("/")
async def root() -> dict[str, str]:
    return {
        "service": "Developer Activity Reporting API",
        "docs": "/docs",
    }
